### ISSUE TITLE
Does not work for the locked device?

### ISSUE THREAD

**Issue by zazor1911** [pathsense/pathsense-samples-android#1]
Hello!
I'm trying to get intent with Broadcast Receiver after the launch of the service, and lock the device, but I get it only when my screen is unlocked. Can help me please?

**Comment by dyerjo** [comment]
Which API are you trying to use?

**Comment by zazor1911** [comment]
Activity API

**Comment by dyerjo** [comment]
You have to register the receiver in the AndroidManifest.xml. You cannot programatically register the receiver.

**Comment by zazor1911** [comment]
Yes, I register receiver like example:
 <receiver
  android:name=".PathsenseActivityUpdateBroadcastReceiver" />

**Comment by dyerjo** [comment]
Can you send me the code so I can look at it?

**Comment by zazor1911** [comment]
What part of the code?
I've done every step of this example: https://github.com/pathsense/pathsense-samples-android/blob/master/pathsense-activitydemo-app/README.md

**Comment by dyerjo** [comment]
It should be working then, in the background or foreground.

What version of Android are you running. Also, what device?

**Comment by zazor1911** [comment]
I tried Samsung galaxy S3, Samsung galaxy S5, Lenovo P780, Sony z3, Android versions 4.4, 4.3 , 5.0, 5.1

**Comment by zazor1911** [comment]
Maybe this is due to lack of resources. So there was a problem on the foreground. Broadcasts stop coming after a while time. Although simple in backgrounds it works.

**Comment by dyerjo** [comment]
No, that is not the issue.

Actually, I know what it is. The demo/sample app is intended to display the results on the screen and run in the foreground. If you go into the MainActivity, you will see the unregistering from the api in the onPause.

If you want it to run in the background, comment out the onPause method. Then it will run indefinitely while the process is alive.

**Comment by zazor1911** [comment]
Yes, I see. But I do not use unregister. I only register broadcast receiver in my main activity.  
Like:  
api = PathsenseLocationProviderApi.getInstance(this);
api.requestActivityUpdates(PathsenseActivityUpdateBroadcastReceiver.class);

**Comment by dyerjo** [comment]
Can you zip up the entire source and android manifest. I can take a look at it. It should work on the devices and OS you specified.

**Comment by zazor1911** [comment]
I'm sorry I can not do it. But that is my Verbose logs which contains "pathsense", they coming than device is locked too.
http://pastebin.com/RUB3GE8K

**Comment by dyerjo** [comment]
Are you using the latest version? 2.0.0.0?

**Comment by zazor1911** [comment]
No, I using 1.0.0.2 version, cause him values is better for us. Last version give fail positive confidence for IN_VEHICLE when I was sitting at the table.

**Comment by dyerjo** [comment]
Can you switch to 2.0.0.0 just to test the same scenario and see if background works? It uses considerably less resources as 1.0.0.2.

**Comment by zazor1911** [comment]
I tried to change, did not help.
http://pastebin.com/tvJaVCS0

**Comment by pablobaxter** [comment]
@zazor1911 Just out of curiosity, when do you call `api.removeActivityUpdates()` in your code?

**Comment by zazor1911** [comment]
That remove activity updates
api.removeActivityUpdates()

**Comment by dyerjo** [comment]
That will remove the activity updates. Are you calling this in your MainActivity?

**Comment by zazor1911** [comment]
And I tried that

```
            if (Intent.ACTION_SCREEN_OFF.equals(action)) {
                Runnable runnable = new Runnable() {
                    public void run() {
                        api.removeActivityUpdates();
                        api.requestActivityUpdates(PathsenseActivityUpdateBroadcastReceiver.class);
                    }
                };

                new Handler().postDelayed(runnable, 5000);

            }
```

**Comment by zazor1911** [comment]
@dyerjo Yes, and that remove them

**Comment by dyerjo** [comment]
For now, comment out all references to api.removeActivityUpdates().

Once, you call api.requestActivityUpdates it will stay registered until you call remove. If you want the updates in the background, you do not need to do anything else.

**Comment by zazor1911** [comment]
Yes, it was before, I did not use the removal. In my opinion the service is running after device is locked too, but broadcast receiver not called. I also checked his work this way from locked device:

```
    private String isServiceActiv(Context context) {
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningServiceInfo service : manager.getRunningServices(Integer.MAX_VALUE)) {
            if (service.service.getClassName().toLowerCase().contains("pathsense")) {
                return service.service.getClassName();
            }
        }
        return null;
```

**Comment by pablobaxter** [comment]
@zazor1911 Can you please email me at pablo@pathsense.com so we can dig deeper into this issue.  Thanks!

**Comment by zazor1911** [comment]
Thanks!
