### ISSUE TITLE
can't receive the broadcast

### ISSUE THREAD

**Issue by waltChang1** [pathsense/pathsense-samples-android#10]
i have called PathsenseLocationProviderApi.getInstance(this).requestInVehicleLocationUpdates(<class>);
and registered my receiver in manifest,but i can't receive the broadcast,

**Comment by pablobaxter** [comment]
This can be due to a few things, so let me ask you a couple of questions first:

- Is location setting set to "High Accuracy"?
- Do you have internet connectivity on your device or the Internet permission in your manifest?
- Are you able to get GPS location where you are testing?
- Are you getting any errors thrown in logcat?

**Comment by waltChang1** [comment]
1)i have opened the GPS
2)i have  internet connectivity and the permission, included the location permission
3)i can get my location info from method " onLocationChanged",
4)there are no errors thrown

my logical steps:
 1)implement gms‘s LocationListener and override onLocationChanged, i can get location from the method
 2) called "LocationServices.FusedLocationApi.requestLocationUpdates()" to update location and called "PathsenseLocationProviderApi.getInstance(this).requestInVehicleLocationUpdates()" to register PathsenseInVehicleLocationUpdateReceiver to get PathsenseInVehicleLocation,but i cant receive the broadcast,it has registered in manifest,
so i dont know why ,confused!

**Comment by waltChang1** [comment]
i have ran the demo of pathsense-samples-android(pathsense-invehiclelocationdemo-app) and successfully, but i can't receive the broadcast too.
Is my test method wrong?or how to test can receive the broadcast ?

**Comment by pablobaxter** [comment]
Can you install the pathsense-invehiclelocationdemo-app APK that comes in the zip with the AAR and see if you get any points?

**Comment by waltChang1** [comment]
i have installed the pathsense-invehiclelocationdemo-app APK that comes in the zip,and only one marker (GroundTruth) is shown,but marker(PathsenseInVehicle) doesn't shown,the broadcast can't be received so that marker(PathsenseInVehicle) can't be shown.
![device-2017-04-25-092914](https://cloud.githubusercontent.com/assets/26158758/25365248/07049576-299a-11e7-8d06-093a79f66cc4.png)

**Comment by pablobaxter** [comment]
What type of device are you using? Also what country are you using this device in? And do you have a second device to test on? Lastly, I don't see a GPS icon at the status bar (indicates GPS is in use). Does it come on for any other app?
