### ISSUE TITLE
Notification group or Intent not configurable

### ISSUE THREAD

**Issue by anti43** [pathsense/pathsense-samples-android#19]
The notification is always there, but not in a group and when user tap it, nothing happens. This is not what a user expects.

**Comment by dyerjo** [comment]
You can now fully customize the foreground notification by implementing ```com.pathsense.android.sdk.location.PathsenseNotificationFactory```.

Please, see [README](https://github.com/pathsense/pathsense-samples-android#how-to-customize-foreground-notification)
