### ISSUE TITLE
Notification settings ignored

### ISSUE THREAD

**Issue by anti43** [pathsense/pathsense-samples-android#20]
The properties

icon_name= drawable/pickrwhite200
oreo_show_notification= false
background_service=true

are ignored. The icon remains the default one and its always in foreground.

**Comment by dyerjo** [comment]
You can now fully customize the foreground notification by implementing ```com.pathsense.android.sdk.location.PathsenseNotificationFactory```.

Please, see [README](https://github.com/pathsense/pathsense-samples-android#how-to-customize-foreground-notification)
