### ISSUE TITLE
pathsense cuts battery drain location

### ISSUE THREAD

**Issue by ebarault** [pathsense/pathsense-samples-android#3]
hi pathsense team!
[in this link](https://www.yahoo.com/tech/pathsense-cuts-battery-drain-location-130006965.html), you show a very promising compairison between battery consumption on a given GPS tracking, with and without pathsense.
Though in your SDK i cannot find what specific functions you're leveraging to achieve this. Would it rely on down sampling the GPS tracking frequency and correcting/snapping the data? (maybe as advertised in iOS Urban Canyon?)  For now we're testing the activity detection feature on Android.

**Comment by farmazon3000** [comment]
@ebarault how can you say what's inside SDK? Do you have source code of it to claim "i cannot find what specific functions you're leveraging to achieve this"?

**Comment by ebarault** [comment]
well, really i do not try to claim anything here @farmazon3000, i'm just really interested in how to get these results and would be happy to test it. But as said for now for Android I don't see in the SDK documentation the features they are talking about in the article, i'm just enquiring. Don't take any offense here please :+1:

**Comment by pablobaxter** [comment]
@ebarault Unfortunately, the low-power location provider you are referring to is on our road map, but we have no timeline for release.  We are still working towards achieving this, although.  If you have any questions or problems with any of our other solutions, please feel free to open another issue here!  Thank you!
