### ISSUE TITLE
Implementation question for the PathsenseGeofenceEvent class

### ISSUE THREAD

**Issue by egmontr** [pathsense/pathsense-samples-android#5]
Can you implement in the PathsenseGeofenceEvent class, that it returns a list of involved geofences at one time and not one by one?
The geofencing event of Google does it so.

Regards
Egmont

**Comment by dyerjo** [comment]
Hi Egmont,

Yes, we will add this to our roadmap and get this out in one of our upcoming releases.

 Thank you,
John Dyer

**Comment by pablobaxter** [comment]
Implemented as of v2.2.0.0
