### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by cpenbe** [pathsense/pathsense-samples-android#8]
Tried your solution but it didn't work as fast as claimed on your site (ie. 2x).
It triggered later than Google. Is there anything we are missing?
Thanks in advance for the solution.

**Comment by pablobaxter** [comment]
Did you perform this test with both Wifi and GPS enabled on the device?

**Comment by cpenbe** [comment]
Thanks Pablo. It seems that it may be due to a device problem. It works good now. I'll be in touch after testing all cases if I get trouble.

**Comment by pablobaxter** [comment]
Awesome! Keep me posted.

**Comment by pablobaxter** [comment]
@ozfloyd Just wanted to check back to make sure everything has gone well with your testing.

**Comment by cpenbe** [comment]
Hi Pablo, thanks for checking, seems good now, even working w/o gps, you're the great!
Btw, next step would be to find a solution for locating with location setting off :)

**Comment by pablobaxter** [comment]
Glad to hear everything went well! I'll be closing this issue now.
