### ISSUE TITLE
Location provider use if not GPS is available

### ISSUE THREAD

**Issue by cpenbe** [pathsense/pathsense-samples-android#9]
Does your location provider solution work without GPS (ie. via Wifi, mobile network etc.) in case GPS is unavailable to use?

**Comment by pablobaxter** [comment]
The Geofence API works without GPS, but performance will be degraded compared to both GPS and WiFi being on. Are you expecting GPS to be turned off, or having the device used in a GPS devoid area?

**Comment by cpenbe** [comment]
Thanks for the answer Pablo. Actually I'm expecting GPS to be turned off to save battery.
